# Generated by Django 3.0.6 on 2020-08-08 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('courseGoal', models.CharField(max_length=30)),
                ('courseMaxNumberOfLearner', models.IntegerField()),
                ('courseOriantationDate', models.DateField()),
                ('courseStartingDate', models.DateField()),
                ('courseFinishingDate', models.DateField()),
                ('courseTotalDuiration', models.CharField(max_length=30)),
                ('courseNumberOfClasses', models.CharField(max_length=30)),
                ('courseClassDuiration', models.CharField(max_length=30)),
                ('courseClassStartTime', models.TimeField()),
                ('courseClassEndTime', models.TimeField()),
                ('courseInstractorId', models.CharField(max_length=50)),
                ('courseInstractorName', models.CharField(max_length=30)),
                ('courseInstractorQualification', models.CharField(max_length=30)),
                ('courseInstractorPhoneNumber', models.CharField(max_length=30)),
                ('coursePriceInTk', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Learnerns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnerId', models.CharField(max_length=50)),
                ('isPaymentValified', models.BooleanField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='courseReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnerId', models.CharField(max_length=50)),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
        ),
    ]
