# Generated by Django 3.0.6 on 2020-08-09 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200809_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereviews',
            name='review',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
