# Generated by Django 3.0.6 on 2020-08-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursereviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereviews',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='learnerns',
            old_name='courses',
            new_name='course',
        ),
    ]
