### Common
server:
  port: 33001

spring:
  application:
    name: elearners.live-backend
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: src/main/resources/static/images

---

### Prod profile

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/elearner?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:L2#j6^%hcyb_?AB}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
email:
  debug: false
  from:
    address: itvillage29@gmail.com
  sender:
    host: smtp.gmail.com
    password: itvillage428854@#
    port: 587
    username: itvillage29@gmail.com
  smtp:
    auth: true
    starttls:
      enable: true
  transport:
    protocol: smtp
---


### Dev profile

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/elearner?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
email:
  debug: false
  from:
    address: itvillage29@gmail.com
  sender:
    host: smtp.gmail.com
    password: itvillage428854@#
    port: 587
    username: itvillage29@gmail.com
  smtp:
    auth: true
    starttls:
      enable: true
  transport:
    protocol: smtp
---
